import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData(
  appBarTheme: const AppBarTheme(
    surfaceTintColor: Colors.transparent,
    titleTextStyle: TextStyle(fontSize: 22.0, fontWeight: FontWeight.w500),
  ),
  scaffoldBackgroundColor: const Color(0xFFFEF7FF),
  colorScheme: const ColorScheme.light(
    primary: Color(0xFF6750A4),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEADDFF),
    onPrimaryContainer: Color(0xFF21005D),
    inversePrimary: Color(0xFFD0BCFF),
    secondary: Color(0xFF625B71),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE8DEF8),
    onSecondaryContainer: Color(0xFF1D192B),
    surface: Color(0xFFFEF7FF),
    onSurface: Color(0xFF1D1B20),
    inverseSurface: Color(0xFF322F35),
    onInverseSurface: Color(0xFFF5EFF7),
    onSurfaceVariant: Color(0xFF49454F),
    background: Colors.white,
    onBackground: Colors.black,
    outline: Color(0xFF79747E),
    outlineVariant: Color(0xFFCAC4D0),
    scrim: Color(0xFF000000),
    shadow: Color(0xFF000000),
    tertiary: Color(0xFF7D5260),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD8E4),
    onTertiaryContainer: Color(0xFF31111D),
    error: Color(0xFFB3261E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFF9DEDC),
    onErrorContainer: Color(0xFF410E0B),
  ),
);
