// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-AgM_TOKG5ogb9dOMY547JPkPVIBhYAE',
    appId: '1:545198127880:web:913ebee88fa0451038cabd',
    messagingSenderId: '545198127880',
    projectId: 'video-sharing-c9850',
    authDomain: 'video-sharing-c9850.firebaseapp.com',
    storageBucket: 'video-sharing-c9850.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFwfohPG2_yHBemhmHnVmU3CKTnSEbW-A',
    appId: '1:545198127880:android:a35b4e9fa6cbc24438cabd',
    messagingSenderId: '545198127880',
    projectId: 'video-sharing-c9850',
    storageBucket: 'video-sharing-c9850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_fkpFiQYvFBIdOIHToNDL-DyHrGidK4',
    appId: '1:545198127880:ios:e4515573c3b705cb38cabd',
    messagingSenderId: '545198127880',
    projectId: 'video-sharing-c9850',
    storageBucket: 'video-sharing-c9850.appspot.com',
    iosBundleId: 'com.example.videoSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_fkpFiQYvFBIdOIHToNDL-DyHrGidK4',
    appId: '1:545198127880:ios:e4515573c3b705cb38cabd',
    messagingSenderId: '545198127880',
    projectId: 'video-sharing-c9850',
    storageBucket: 'video-sharing-c9850.appspot.com',
    iosBundleId: 'com.example.videoSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-AgM_TOKG5ogb9dOMY547JPkPVIBhYAE',
    appId: '1:545198127880:web:bc4c9147d6dd690938cabd',
    messagingSenderId: '545198127880',
    projectId: 'video-sharing-c9850',
    authDomain: 'video-sharing-c9850.firebaseapp.com',
    storageBucket: 'video-sharing-c9850.appspot.com',
  );
}
